// client/src/components/Home.vue
<template>
    <div>
        <h1>{{ msg }}</h1>
        <a href="https://games-library-app.onrender.com/game">Games Library</a>
    </div>
</template>
<script>
import axios from 'axios';
export default {
   name:'Home',
   data(){
    return{
        msg:"",
    }
   },
   methods:{
     getRes(){
        const path = "https://games-library-app.onrender.com";
        axios.get(path)
        .then((res)=> this.msg = res.data)
        .catch((error)=> console.log(error));
     }
   },
   created(){
    this.getRes();
   }
}
</script>
<style scoped>
h1{
    text-align: center;
}
a{
    display: block;
    font-size: 23px;
    text-align: center;
    text-decoration: none;
}
a:hover{
    color: red;
}
</style>

// client/src/components/Home.jsx
import { useEffect, useState } from "react";
import axios from "axios";
import { Link } from "react-router-dom";

export default function Home() {
  const [msg, setMsg] = useState("");

  const getRes = () => {
    axios
      .get("https://games-library-app.onrender.com")
      .then((res) => setMsg(res.data))
      .catch((err) => console.log(err));
  };

  useEffect(() => {
    getRes();
  }, []);

  return (
    <div>
      <h1 style={{ textAlign: "center" }}>{msg}</h1>
      <Link
        to="/game"
        style={{
          display: "block",
          fontSize: "23px",
          textAlign: "center",
          textDecoration: "none",
        }}
      >
        Games Library
      </Link>
    </div>
  );
}
